### ISSUE TITLE
Create endpoint: DELETE /room/id - clears  all chats in a room

### ISSUE THREAD

**Issue by keerat21** [keerat21/mvp-backend#4]

**Comment by pauljones0** [comment]
![Image](https://github.com/user-attachments/assets/be14a9ac-23ae-4398-92c2-6d57b6bffd26)

**Comment by pauljones0** [comment]
![Image](https://github.com/user-attachments/assets/24f5b546-4dbf-451f-b61d-2a0d9d098e0f)
